### ISSUE TITLE
[BUG] ~ `User` doesn't exist??

### ISSUE THREAD

**Issue by 19wintersp** [RayhanADev/ReplAPI.it#33]
**Describe the bug**
The `User` class doesn't appear to *work*, in that it is undefined.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a node script
2. Install replapi-it
3. Paste in this script:
```js
const { User } = require("replapi-it");
console.log(`User is ${ User }`);
```
4. Logged to console will be "User is undefined"

**Expected behaviour**
If you were to follow these steps, "[class User]" or similar should be output.

**Server**
 - OS: GNU/Linux x86-64 Ubuntu 18.04 Bionic
 - Runtime: NodeJS 12.22.1
 - Platform: Replit

**Additional context**
This seems to be recent, and it comes with a few other problems I've experienced; I was only made aware of these issues yesterday due to error pages on my site.

**Comment by RayhanADev** [comment]
@19wintersp 
Heya! **Would you care to tell me what version of the package you are using?** That might help confirm your problems. Also if you aren't aware the package is actually undergoing some major revamping and previous versions and documentation have been ~~accidentally~~ depreciated a bit too early.

If you are using the latest version of the package try this:
```js
const replapi = require('replapi-it')(); // Invoke the function

const myUser = new replapi.User('19wintersp'); // Use like normal
```

I would encourage you to take a look at [this](https://github.com/RayhanADev/ReplAPI.it/blob/main/index.js) and [this](https://github.com/RayhanADev/ReplAPI.it/blob/main/src/classes/User.js) to make sure none of your other code broke.

The major changes to the package will be happening on [this](https://github.com/RayhanADev/ReplAPI.it/tree/RayhanADev-Major-Refactors) branch and once I finish and merge it the next version of the package will come out!

Sorry about the problem and confusion, I'll go ahead and leave a reminder on the README so that no one else has a problem :).

**Comment by 19wintersp** [comment]
Thanks for the speedy response, I was wondering what had happened as I hadn't seen any notices in the README. For some reason, I was having issues with an older version on the project (might have been something else), so I tried to update it, and then ran into this issue.

I've applied the change you suggested, however now I'm getting this:

```
TypeError: Cannot read property 'userByUsername' of undefined
    at User.profileData (node_modules/replapi-it/src/classes/User.js:29:18)
```

I'll probably just disable the system for now until the changes have been completed.

**Comment by googol88** [comment]
It seems as if the entire API is down. I encountered no problems with it until yesterday, but I haven’t changed the package version or anything like that.

**Comment by googol88** [comment]
@RayhanADev it’s still down 😔 where is it hosted on? Might want to restart the server

**Comment by 19wintersp** [comment]
@googol88 That's not really what they mean by "down", the package is currently nonfunctional

**Comment by RayhanADev** [comment]
@googol88 Yep, what @19wintersp said it is severely broken and I believe out of the blue there are changes occurring to the Replit API. I'm patching a lot of stuff but right now there are a bunch of holes in my package smh.

**Comment by RayhanADev** [comment]
@googol88 @19wintersp I mentioned this in another issue, so letting you know here too:
> I have good news. I have almost finished the next version of ReplAPI.it, so you can expect it to be released before tonight. It shouldn't take long to finish my final changes.

**Comment by RayhanADev** [comment]
Okeydokey, here we go:
@googol88 @19wintersp @darkdarcool

I just released the package on NPM. If you have a moment could you please try out this code:
```js
import ReplAPI from 'replapi-it'
const replapi = ReplAPI({
  username: 'your-username-here',
});

const myTestClass = new replapi.User('your-username-here');

async function myTestFunction() {
  const info = await myTestClass.userGraphQLDataFull();
  console.log(info);
}

myTestFunction();
```

Note that it is using ES6. Be sure to use the `--experimental-modules` flag when you run the file or create a `.replit` file with the following:
```
run = "node index.js --experimental-modules"
```
To use the run button in Replit.


Let me know how it goes!

**Comment by 19wintersp** [comment]
@RayhanADev Awesome, looks great! Nice to see ES Modules being used here too.

I'll update the service now, and see how it goes.

**Comment by RayhanADev** [comment]
@19wintersp yay glad to hear that it works. I'll keep this open until your service is up and running just to make sure any kinks are worked out :D.

**Comment by 19wintersp** [comment]
@RayhanADev Apologies if this is obvious, but could you enlighten me as to how I can change `userAttributes` defined in "src/utils/constants.js"?

**Comment by RayhanADev** [comment]
No need to apologize, you are not supposed to be able to change the constants. Is there a specific reason you need to change them?

**Comment by 19wintersp** [comment]
I just wanted to be able to port my original code, whilst making as few changes as possible. It *should* be possible to do it without changing these constants, but that would require some refactoring. Thanks for letting me know

**Comment by RayhanADev** [comment]
Okay, no problem.
