### ISSUE TITLE
[BUG] User is not a constructor  

### ISSUE THREAD

**Issue by darkdarcool** [RayhanADev/ReplAPI.it#36]
**Describe the bug**
In the shell I cant use the package because it says that `User` is not a contructor.
**To Reproduce**
1. Make a new repl with the cycle code in your readme
2. Run it

**Expected behavior**
I wanted it to return my cycle data
**Screenshots**
![image](https://user-images.githubusercontent.com/66882633/115297178-c0230000-a110-11eb-977d-4fe7747b1e73.png)

**Desktop (please complete the following information):**
 - Chromebook(im usually on mac)
 - Chrome
 - Latest

**Comment by darkdarcool** [comment]
#33 
it is related to this

**Comment by darkdarcool** [comment]
also @RayhanADev, can you give me a version of were all of this works in the meantime? I think it would be helpful!

**Comment by RayhanADev** [comment]
Heya @darkdarcool! 

I have good news. I have almost finished the next version of ReplAPI.it, so you can expect it to be released before tonight. It shouldn't take long to finish my final changes.

If it is immediately needed, I can't name a version that works off the top of my head so you might want to just test backward versions until you find one that works, however it shouldn't be much longer till this is finished.

**Comment by darkdarcool** [comment]
noice, I will wait until tomorrow and look at the packages history on npm to make sure I'm using the right one, thanks!(it's for my 100 cycles special, and I hit 100 cycles!)

**Comment by RayhanADev** [comment]
Nice!! I just rolled out version 2.0.0 of ReplAPI.it and I'm about to release the release notes for it.

**Comment by darkdarcool** [comment]
nice! i guess it will be out for tomorrow, so I'll just do `npm install replapi-it@latest` and I think it'll work! thx!!

**Comment by RayhanADev** [comment]
@darkdarcool hahaha well, it's not that simple....
Check this out: https://github.com/RayhanADev/ReplAPI.it/releases/tag/v2.0.0

**Comment by darkdarcool** [comment]
or can you give me that code for cycles and I can try to just make a posts thing? maybe I'll invite you the the project on wednesday or thursday and have you help me out. that's a maybe though, if you wanna?

**Comment by RayhanADev** [comment]
You might have change your code just a *little* bit.
and yeah I'd be glad to help out ~~it's the least I can do after putting everyone in this situation~~. xD

**Comment by darkdarcool** [comment]
lol. And you don't have to worry about putting everyone in this situation, lol. It's just a mistake. And I'll inv you probs on wednesday.(somewhere around 8am Pacific Daylight Time or so?)

**Comment by RayhanADev** [comment]
Yeah tomorrow works, we're doing state testing in like 10 more minutes so yeah. Tomorrow ;D.

**Comment by darkdarcool** [comment]
lol my school isn't doing it this year :)))
